// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8PAVCq-SYD8dnIR5dAJloc7jCmeWYg3E',
    appId: '1:1050441103714:web:782fd30320a85995d9543b',
    messagingSenderId: '1050441103714',
    projectId: 'app-flutter-e5ebc',
    authDomain: 'app-flutter-e5ebc.firebaseapp.com',
    databaseURL: 'https://app-flutter-e5ebc-default-rtdb.firebaseio.com',
    storageBucket: 'app-flutter-e5ebc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlCnyn1fEnvJ8papXjqqES_DTU4c0pqs',
    appId: '1:1050441103714:android:cd25a7dba723c539d9543b',
    messagingSenderId: '1050441103714',
    projectId: 'app-flutter-e5ebc',
    databaseURL: 'https://app-flutter-e5ebc-default-rtdb.firebaseio.com',
    storageBucket: 'app-flutter-e5ebc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8PAVCq-SYD8dnIR5dAJloc7jCmeWYg3E',
    appId: '1:1050441103714:web:ade065f909955d78d9543b',
    messagingSenderId: '1050441103714',
    projectId: 'app-flutter-e5ebc',
    authDomain: 'app-flutter-e5ebc.firebaseapp.com',
    databaseURL: 'https://app-flutter-e5ebc-default-rtdb.firebaseio.com',
    storageBucket: 'app-flutter-e5ebc.firebasestorage.app',
  );

}